"""Testing for Egg Generator"""

from src import egg_generator


def test_genderless() -> None:
    """Test generate with Genderless gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "Genderless",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Lonely",
            "Ability": "95",
            "HP": "2",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "11",
            "SpD": "10",
            "Spe": "-2",
            "Gender": "-",
            "EC": "AEF10229",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "68",
            "HP": "29",
            "Atk": "-2",
            "Def": "9",
            "SpA": "22",
            "SpD": "-2",
            "Spe": "-1",
            "Gender": "-",
            "EC": "CA975BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "23",
            "HP": "-1",
            "Atk": "1",
            "Def": "-1",
            "SpA": "-1",
            "SpD": "0",
            "Spe": "21",
            "Gender": "-",
            "EC": "B8CC5D3B",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Quirky",
            "Ability": "79",
            "HP": "24",
            "Atk": "-1",
            "Def": "16",
            "SpA": "-1",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "-",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "19",
            "HP": "-2",
            "Atk": "-2",
            "Def": "22",
            "SpA": "3",
            "SpD": "18",
            "Spe": "-1",
            "Gender": "-",
            "EC": "4BE26514",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "14",
            "HP": "3",
            "Atk": "15",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "1",
            "Spe": "-2",
            "Gender": "-",
            "EC": "A3F96E46",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "47",
            "HP": "26",
            "Atk": "-1",
            "Def": "25",
            "SpA": "20",
            "SpD": "-1",
            "Spe": "-2",
            "Gender": "-",
            "EC": "702602E6",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "7",
            "HP": "-2",
            "Atk": "16",
            "Def": "15",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "-",
            "EC": "BAEDE6ED",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "78",
            "HP": "25",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "0",
            "SpD": "17",
            "Spe": "-2",
            "Gender": "-",
            "EC": "719C1DD",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "52",
            "HP": "21",
            "Atk": "-1",
            "Def": "16",
            "SpA": "23",
            "SpD": "-2",
            "Spe": "-2",
            "Gender": "-",
            "EC": "68922B4",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "13",
            "HP": "-2",
            "Atk": "30",
            "Def": "-1",
            "SpA": "31",
            "SpD": "-1",
            "Spe": "2",
            "Gender": "-",
            "EC": "309D89B5",
        },
        {
            "Advances": "6394",
            "Egg Seed": "FE3B1FBD",
            "PID": "4932AD3F",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "22",
            "HP": "13",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "28",
            "SpD": "13",
            "Spe": "-2",
            "Gender": "-",
            "EC": "3CDED582",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "53",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "-",
            "EC": "6298AAD3",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "21",
            "HP": "26",
            "Atk": "6",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "-",
            "EC": "A4BACBA5",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "53",
            "HP": "26",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "29",
            "Spe": "19",
            "Gender": "-",
            "EC": "4644661D",
        },
    ]


def test_100_f() -> None:
    """Test generate with 100% F gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "100% F",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Lonely",
            "Ability": "95",
            "HP": "2",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "11",
            "SpD": "10",
            "Spe": "-2",
            "Gender": "F",
            "EC": "AEF10229",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "68",
            "HP": "29",
            "Atk": "-2",
            "Def": "9",
            "SpA": "22",
            "SpD": "-2",
            "Spe": "-1",
            "Gender": "F",
            "EC": "CA975BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "23",
            "HP": "-1",
            "Atk": "1",
            "Def": "-1",
            "SpA": "-1",
            "SpD": "0",
            "Spe": "21",
            "Gender": "F",
            "EC": "B8CC5D3B",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Quirky",
            "Ability": "79",
            "HP": "24",
            "Atk": "-1",
            "Def": "16",
            "SpA": "-1",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "F",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "19",
            "HP": "-2",
            "Atk": "-2",
            "Def": "22",
            "SpA": "3",
            "SpD": "18",
            "Spe": "-1",
            "Gender": "F",
            "EC": "4BE26514",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "14",
            "HP": "3",
            "Atk": "15",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "1",
            "Spe": "-2",
            "Gender": "F",
            "EC": "A3F96E46",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "47",
            "HP": "26",
            "Atk": "-1",
            "Def": "25",
            "SpA": "20",
            "SpD": "-1",
            "Spe": "-2",
            "Gender": "F",
            "EC": "702602E6",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "7",
            "HP": "-2",
            "Atk": "16",
            "Def": "15",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "F",
            "EC": "BAEDE6ED",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "78",
            "HP": "25",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "0",
            "SpD": "17",
            "Spe": "-2",
            "Gender": "F",
            "EC": "719C1DD",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "52",
            "HP": "21",
            "Atk": "-1",
            "Def": "16",
            "SpA": "23",
            "SpD": "-2",
            "Spe": "-2",
            "Gender": "F",
            "EC": "68922B4",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "13",
            "HP": "-2",
            "Atk": "30",
            "Def": "-1",
            "SpA": "31",
            "SpD": "-1",
            "Spe": "2",
            "Gender": "F",
            "EC": "309D89B5",
        },
        {
            "Advances": "6394",
            "Egg Seed": "FE3B1FBD",
            "PID": "4932AD3F",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "22",
            "HP": "13",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "28",
            "SpD": "13",
            "Spe": "-2",
            "Gender": "F",
            "EC": "3CDED582",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "53",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "F",
            "EC": "6298AAD3",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "21",
            "HP": "26",
            "Atk": "6",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "F",
            "EC": "A4BACBA5",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "53",
            "HP": "26",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "29",
            "Spe": "19",
            "Gender": "F",
            "EC": "4644661D",
        },
    ]


def test_25_m_75_f() -> None:
    """Test generate with 25% M / 75% F gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "25% M / 75% F",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "42",
            "Egg Seed": "DEF71524",
            "PID": "9C78787A",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "40",
            "HP": "-2",
            "Atk": "-1",
            "Def": "5",
            "SpA": "-1",
            "SpD": "27",
            "Spe": "2",
            "Gender": "M",
            "EC": "462A4A82",
        },
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "82",
            "HP": "-2",
            "Atk": "-1",
            "Def": "11",
            "SpA": "-2",
            "SpD": "31",
            "Spe": "9",
            "Gender": "F",
            "EC": "59894588",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Bashful",
            "Ability": "49",
            "HP": "10",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "26",
            "SpD": "9",
            "Spe": "-2",
            "Gender": "F",
            "EC": "691E42BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "44",
            "HP": "-2",
            "Atk": "20",
            "Def": "-1",
            "SpA": "0",
            "SpD": "-2",
            "Spe": "27",
            "Gender": "M",
            "EC": "4E8C72C",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Naughty",
            "Ability": "93",
            "HP": "-2",
            "Atk": "20",
            "Def": "-2",
            "SpA": "3",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "15",
            "HP": "-1",
            "Atk": "-2",
            "Def": "22",
            "SpA": "-1",
            "SpD": "18",
            "Spe": "15",
            "Gender": "M",
            "EC": "4BE26514",
        },
        {
            "Advances": "4404",
            "Egg Seed": "3172E7DF",
            "PID": "3A96DE93",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "67",
            "HP": "-1",
            "Atk": "-2",
            "Def": "25",
            "SpA": "28",
            "SpD": "12",
            "Spe": "-1",
            "Gender": "M",
            "EC": "6A903067",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Naive",
            "Ability": "76",
            "HP": "15",
            "Atk": "-2",
            "Def": "10",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "6",
            "Gender": "F",
            "EC": "30F799A5",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "99",
            "HP": "-2",
            "Atk": "-1",
            "Def": "18",
            "SpA": "6",
            "SpD": "-2",
            "Spe": "23",
            "Gender": "M",
            "EC": "5E327AB3",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "16",
            "HP": "-2",
            "Atk": "-1",
            "Def": "12",
            "SpA": "-1",
            "SpD": "6",
            "Spe": "13",
            "Gender": "M",
            "EC": "F19E066",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "50",
            "HP": "7",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "30",
            "Spe": "29",
            "Gender": "F",
            "EC": "346575F7",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Brave",
            "Ability": "72",
            "HP": "15",
            "Atk": "-2",
            "Def": "23",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "20",
            "Gender": "F",
            "EC": "9A249237",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "46",
            "HP": "-1",
            "Atk": "9",
            "Def": "-1",
            "SpA": "17",
            "SpD": "-1",
            "Spe": "28",
            "Gender": "F",
            "EC": "BE9D242",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "39",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "F",
            "EC": "6298AAD3",
        },
        {
            "Advances": "7478",
            "Egg Seed": "CDCF42EC",
            "PID": "96407242",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "62",
            "HP": "-1",
            "Atk": "-2",
            "Def": "12",
            "SpA": "0",
            "SpD": "10",
            "Spe": "-1",
            "Gender": "F",
            "EC": "78A046A4",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Gentle",
            "Ability": "12",
            "HP": "-1",
            "Atk": "12",
            "Def": "31",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "F",
            "EC": "9B3FC588",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "73",
            "HP": "17",
            "Atk": "-1",
            "Def": "-2",
            "SpA": "29",
            "SpD": "-1",
            "Spe": "29",
            "Gender": "M",
            "EC": "442BF368",
        },
    ]


def test_50_m_50_f() -> None:
    """Test generate with 50% M / 50% F gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "50% M / 50% F",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "42",
            "Egg Seed": "DEF71524",
            "PID": "9C78787A",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "40",
            "HP": "-2",
            "Atk": "-1",
            "Def": "5",
            "SpA": "-1",
            "SpD": "27",
            "Spe": "2",
            "Gender": "M",
            "EC": "462A4A82",
        },
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "82",
            "HP": "-2",
            "Atk": "-1",
            "Def": "11",
            "SpA": "-2",
            "SpD": "31",
            "Spe": "9",
            "Gender": "M",
            "EC": "59894588",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Bashful",
            "Ability": "49",
            "HP": "10",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "26",
            "SpD": "9",
            "Spe": "-2",
            "Gender": "F",
            "EC": "691E42BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "44",
            "HP": "-2",
            "Atk": "20",
            "Def": "-1",
            "SpA": "0",
            "SpD": "-2",
            "Spe": "27",
            "Gender": "M",
            "EC": "4E8C72C",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Naughty",
            "Ability": "93",
            "HP": "-2",
            "Atk": "20",
            "Def": "-2",
            "SpA": "3",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "15",
            "HP": "-1",
            "Atk": "-2",
            "Def": "22",
            "SpA": "-1",
            "SpD": "18",
            "Spe": "15",
            "Gender": "M",
            "EC": "4BE26514",
        },
        {
            "Advances": "4404",
            "Egg Seed": "3172E7DF",
            "PID": "3A96DE93",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "67",
            "HP": "-1",
            "Atk": "-2",
            "Def": "25",
            "SpA": "28",
            "SpD": "12",
            "Spe": "-1",
            "Gender": "M",
            "EC": "6A903067",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Naive",
            "Ability": "76",
            "HP": "15",
            "Atk": "-2",
            "Def": "10",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "6",
            "Gender": "M",
            "EC": "30F799A5",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "99",
            "HP": "-2",
            "Atk": "-1",
            "Def": "18",
            "SpA": "6",
            "SpD": "-2",
            "Spe": "23",
            "Gender": "M",
            "EC": "5E327AB3",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "16",
            "HP": "-2",
            "Atk": "-1",
            "Def": "12",
            "SpA": "-1",
            "SpD": "6",
            "Spe": "13",
            "Gender": "M",
            "EC": "F19E066",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "50",
            "HP": "7",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "30",
            "Spe": "29",
            "Gender": "F",
            "EC": "346575F7",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Brave",
            "Ability": "72",
            "HP": "15",
            "Atk": "-2",
            "Def": "23",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "20",
            "Gender": "F",
            "EC": "9A249237",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "46",
            "HP": "-1",
            "Atk": "9",
            "Def": "-1",
            "SpA": "17",
            "SpD": "-1",
            "Spe": "28",
            "Gender": "F",
            "EC": "BE9D242",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "39",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "M",
            "EC": "6298AAD3",
        },
        {
            "Advances": "7478",
            "Egg Seed": "CDCF42EC",
            "PID": "96407242",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "62",
            "HP": "-1",
            "Atk": "-2",
            "Def": "12",
            "SpA": "0",
            "SpD": "10",
            "Spe": "-1",
            "Gender": "M",
            "EC": "78A046A4",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Gentle",
            "Ability": "12",
            "HP": "-1",
            "Atk": "12",
            "Def": "31",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "F",
            "EC": "9B3FC588",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "73",
            "HP": "17",
            "Atk": "-1",
            "Def": "-2",
            "SpA": "29",
            "SpD": "-1",
            "Spe": "29",
            "Gender": "M",
            "EC": "442BF368",
        },
    ]


def test_75_m_25_f() -> None:
    """Test generate with 75% M / 25% F gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "75% M / 25% F",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "42",
            "Egg Seed": "DEF71524",
            "PID": "9C78787A",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "40",
            "HP": "-2",
            "Atk": "-1",
            "Def": "5",
            "SpA": "-1",
            "SpD": "27",
            "Spe": "2",
            "Gender": "M",
            "EC": "462A4A82",
        },
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "82",
            "HP": "-2",
            "Atk": "-1",
            "Def": "11",
            "SpA": "-2",
            "SpD": "31",
            "Spe": "9",
            "Gender": "M",
            "EC": "59894588",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Bashful",
            "Ability": "49",
            "HP": "10",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "26",
            "SpD": "9",
            "Spe": "-2",
            "Gender": "M",
            "EC": "691E42BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "44",
            "HP": "-2",
            "Atk": "20",
            "Def": "-1",
            "SpA": "0",
            "SpD": "-2",
            "Spe": "27",
            "Gender": "M",
            "EC": "4E8C72C",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Naughty",
            "Ability": "93",
            "HP": "-2",
            "Atk": "20",
            "Def": "-2",
            "SpA": "3",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "15",
            "HP": "-1",
            "Atk": "-2",
            "Def": "22",
            "SpA": "-1",
            "SpD": "18",
            "Spe": "15",
            "Gender": "M",
            "EC": "4BE26514",
        },
        {
            "Advances": "4404",
            "Egg Seed": "3172E7DF",
            "PID": "3A96DE93",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "67",
            "HP": "-1",
            "Atk": "-2",
            "Def": "25",
            "SpA": "28",
            "SpD": "12",
            "Spe": "-1",
            "Gender": "M",
            "EC": "6A903067",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Naive",
            "Ability": "76",
            "HP": "15",
            "Atk": "-2",
            "Def": "10",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "6",
            "Gender": "M",
            "EC": "30F799A5",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "99",
            "HP": "-2",
            "Atk": "-1",
            "Def": "18",
            "SpA": "6",
            "SpD": "-2",
            "Spe": "23",
            "Gender": "M",
            "EC": "5E327AB3",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "16",
            "HP": "-2",
            "Atk": "-1",
            "Def": "12",
            "SpA": "-1",
            "SpD": "6",
            "Spe": "13",
            "Gender": "M",
            "EC": "F19E066",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "50",
            "HP": "7",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "30",
            "Spe": "29",
            "Gender": "F",
            "EC": "346575F7",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Brave",
            "Ability": "72",
            "HP": "15",
            "Atk": "-2",
            "Def": "23",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "20",
            "Gender": "M",
            "EC": "9A249237",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "46",
            "HP": "-1",
            "Atk": "9",
            "Def": "-1",
            "SpA": "17",
            "SpD": "-1",
            "Spe": "28",
            "Gender": "F",
            "EC": "BE9D242",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "39",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "M",
            "EC": "6298AAD3",
        },
        {
            "Advances": "7478",
            "Egg Seed": "CDCF42EC",
            "PID": "96407242",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "62",
            "HP": "-1",
            "Atk": "-2",
            "Def": "12",
            "SpA": "0",
            "SpD": "10",
            "Spe": "-1",
            "Gender": "M",
            "EC": "78A046A4",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Gentle",
            "Ability": "12",
            "HP": "-1",
            "Atk": "12",
            "Def": "31",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "M",
            "EC": "9B3FC588",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "73",
            "HP": "17",
            "Atk": "-1",
            "Def": "-2",
            "SpA": "29",
            "SpD": "-1",
            "Spe": "29",
            "Gender": "M",
            "EC": "442BF368",
        },
    ]


def test_88_m_12_f() -> None:
    """Test generate with 88% M / 12% F gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "88% M / 12% F",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "42",
            "Egg Seed": "DEF71524",
            "PID": "9C78787A",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "40",
            "HP": "-2",
            "Atk": "-1",
            "Def": "5",
            "SpA": "-1",
            "SpD": "27",
            "Spe": "2",
            "Gender": "M",
            "EC": "462A4A82",
        },
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "82",
            "HP": "-2",
            "Atk": "-1",
            "Def": "11",
            "SpA": "-2",
            "SpD": "31",
            "Spe": "9",
            "Gender": "M",
            "EC": "59894588",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Bashful",
            "Ability": "49",
            "HP": "10",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "26",
            "SpD": "9",
            "Spe": "-2",
            "Gender": "M",
            "EC": "691E42BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "44",
            "HP": "-2",
            "Atk": "20",
            "Def": "-1",
            "SpA": "0",
            "SpD": "-2",
            "Spe": "27",
            "Gender": "M",
            "EC": "4E8C72C",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Naughty",
            "Ability": "93",
            "HP": "-2",
            "Atk": "20",
            "Def": "-2",
            "SpA": "3",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "15",
            "HP": "-1",
            "Atk": "-2",
            "Def": "22",
            "SpA": "-1",
            "SpD": "18",
            "Spe": "15",
            "Gender": "M",
            "EC": "4BE26514",
        },
        {
            "Advances": "4404",
            "Egg Seed": "3172E7DF",
            "PID": "3A96DE93",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "67",
            "HP": "-1",
            "Atk": "-2",
            "Def": "25",
            "SpA": "28",
            "SpD": "12",
            "Spe": "-1",
            "Gender": "M",
            "EC": "6A903067",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Naive",
            "Ability": "76",
            "HP": "15",
            "Atk": "-2",
            "Def": "10",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "6",
            "Gender": "M",
            "EC": "30F799A5",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "99",
            "HP": "-2",
            "Atk": "-1",
            "Def": "18",
            "SpA": "6",
            "SpD": "-2",
            "Spe": "23",
            "Gender": "M",
            "EC": "5E327AB3",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "16",
            "HP": "-2",
            "Atk": "-1",
            "Def": "12",
            "SpA": "-1",
            "SpD": "6",
            "Spe": "13",
            "Gender": "M",
            "EC": "F19E066",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "50",
            "HP": "7",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "30",
            "Spe": "29",
            "Gender": "M",
            "EC": "346575F7",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Brave",
            "Ability": "72",
            "HP": "15",
            "Atk": "-2",
            "Def": "23",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "20",
            "Gender": "M",
            "EC": "9A249237",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "46",
            "HP": "-1",
            "Atk": "9",
            "Def": "-1",
            "SpA": "17",
            "SpD": "-1",
            "Spe": "28",
            "Gender": "F",
            "EC": "BE9D242",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "39",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "M",
            "EC": "6298AAD3",
        },
        {
            "Advances": "7478",
            "Egg Seed": "CDCF42EC",
            "PID": "96407242",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "62",
            "HP": "-1",
            "Atk": "-2",
            "Def": "12",
            "SpA": "0",
            "SpD": "10",
            "Spe": "-1",
            "Gender": "M",
            "EC": "78A046A4",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Gentle",
            "Ability": "12",
            "HP": "-1",
            "Atk": "12",
            "Def": "31",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "M",
            "EC": "9B3FC588",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "73",
            "HP": "17",
            "Atk": "-1",
            "Def": "-2",
            "SpA": "29",
            "SpD": "-1",
            "Spe": "29",
            "Gender": "M",
            "EC": "442BF368",
        },
    ]


def test_nidoran_vi() -> None:
    """Test generate with Nidoran / VI gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "Nidoran / VI",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "42",
            "Egg Seed": "DEF71524",
            "PID": "9C78787A",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "40",
            "HP": "-2",
            "Atk": "-1",
            "Def": "5",
            "SpA": "-1",
            "SpD": "27",
            "Spe": "2",
            "Gender": "M",
            "EC": "462A4A82",
        },
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "82",
            "HP": "-2",
            "Atk": "-1",
            "Def": "11",
            "SpA": "-2",
            "SpD": "31",
            "Spe": "9",
            "Gender": "F",
            "EC": "59894588",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Bashful",
            "Ability": "49",
            "HP": "10",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "26",
            "SpD": "9",
            "Spe": "-2",
            "Gender": "F",
            "EC": "691E42BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "44",
            "HP": "-2",
            "Atk": "20",
            "Def": "-1",
            "SpA": "0",
            "SpD": "-2",
            "Spe": "27",
            "Gender": "F",
            "EC": "4E8C72C",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Naughty",
            "Ability": "93",
            "HP": "-2",
            "Atk": "20",
            "Def": "-2",
            "SpA": "3",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "F",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "15",
            "HP": "-1",
            "Atk": "-2",
            "Def": "22",
            "SpA": "-1",
            "SpD": "18",
            "Spe": "15",
            "Gender": "F",
            "EC": "4BE26514",
        },
        {
            "Advances": "4404",
            "Egg Seed": "3172E7DF",
            "PID": "3A96DE93",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "67",
            "HP": "-1",
            "Atk": "-2",
            "Def": "25",
            "SpA": "28",
            "SpD": "12",
            "Spe": "-1",
            "Gender": "F",
            "EC": "6A903067",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Naive",
            "Ability": "76",
            "HP": "15",
            "Atk": "-2",
            "Def": "10",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "6",
            "Gender": "F",
            "EC": "30F799A5",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "99",
            "HP": "-2",
            "Atk": "-1",
            "Def": "18",
            "SpA": "6",
            "SpD": "-2",
            "Spe": "23",
            "Gender": "F",
            "EC": "5E327AB3",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "16",
            "HP": "-2",
            "Atk": "-1",
            "Def": "12",
            "SpA": "-1",
            "SpD": "6",
            "Spe": "13",
            "Gender": "M",
            "EC": "F19E066",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "50",
            "HP": "7",
            "Atk": "-2",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "30",
            "Spe": "29",
            "Gender": "F",
            "EC": "346575F7",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Brave",
            "Ability": "72",
            "HP": "15",
            "Atk": "-2",
            "Def": "23",
            "SpA": "-2",
            "SpD": "-2",
            "Spe": "20",
            "Gender": "F",
            "EC": "9A249237",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "46",
            "HP": "-1",
            "Atk": "9",
            "Def": "-1",
            "SpA": "17",
            "SpD": "-1",
            "Spe": "28",
            "Gender": "M",
            "EC": "BE9D242",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "39",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "M",
            "EC": "6298AAD3",
        },
        {
            "Advances": "7478",
            "Egg Seed": "CDCF42EC",
            "PID": "96407242",
            "Shiny": "Yes",
            "Nature": "Careful",
            "Ability": "62",
            "HP": "-1",
            "Atk": "-2",
            "Def": "12",
            "SpA": "0",
            "SpD": "10",
            "Spe": "-1",
            "Gender": "M",
            "EC": "78A046A4",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Gentle",
            "Ability": "12",
            "HP": "-1",
            "Atk": "12",
            "Def": "31",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "F",
            "EC": "9B3FC588",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Adamant",
            "Ability": "73",
            "HP": "17",
            "Atk": "-1",
            "Def": "-2",
            "SpA": "29",
            "SpD": "-1",
            "Spe": "29",
            "Gender": "M",
            "EC": "442BF368",
        },
    ]


def test_100_m() -> None:
    """Test generate with 100% M gender ratio"""

    shinies = egg_generator.generate(
        12345,
        54321,
        True,
        True,
        "The two seem to get along very well",
        "100% M",
        True,
        0x1234567887654321,
        0x8765432112345678,
        0,
        10000,
    )

    assert shinies == [
        {
            "Advances": "928",
            "Egg Seed": "1D537A02",
            "PID": "2EDCCAD2",
            "Shiny": "Yes",
            "Nature": "Lonely",
            "Ability": "95",
            "HP": "2",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "11",
            "SpD": "10",
            "Spe": "-2",
            "Gender": "M",
            "EC": "AEF10229",
        },
        {
            "Advances": "1039",
            "Egg Seed": "B0E70D41",
            "PID": "72AC96A9",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "68",
            "HP": "29",
            "Atk": "-2",
            "Def": "9",
            "SpA": "22",
            "SpD": "-2",
            "Spe": "-1",
            "Gender": "M",
            "EC": "CA975BB",
        },
        {
            "Advances": "1662",
            "Egg Seed": "70848BAD",
            "PID": "AF784B7B",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "23",
            "HP": "-1",
            "Atk": "1",
            "Def": "-1",
            "SpA": "-1",
            "SpD": "0",
            "Spe": "21",
            "Gender": "M",
            "EC": "B8CC5D3B",
        },
        {
            "Advances": "2513",
            "Egg Seed": "7B08D2C3",
            "PID": "4E5AAA59",
            "Shiny": "Yes",
            "Nature": "Quirky",
            "Ability": "79",
            "HP": "24",
            "Atk": "-1",
            "Def": "16",
            "SpA": "-1",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "DECDB15F",
        },
        {
            "Advances": "4344",
            "Egg Seed": "C8EB51E4",
            "PID": "2CADC8A4",
            "Shiny": "Yes",
            "Nature": "Rash",
            "Ability": "19",
            "HP": "-2",
            "Atk": "-2",
            "Def": "22",
            "SpA": "3",
            "SpD": "18",
            "Spe": "-1",
            "Gender": "M",
            "EC": "4BE26514",
        },
        {
            "Advances": "4545",
            "Egg Seed": "4711663C",
            "PID": "A85F4C5A",
            "Shiny": "Yes",
            "Nature": "Impish",
            "Ability": "14",
            "HP": "3",
            "Atk": "15",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "1",
            "Spe": "-2",
            "Gender": "M",
            "EC": "A3F96E46",
        },
        {
            "Advances": "4655",
            "Egg Seed": "C8965ED3",
            "PID": "ACB548B0",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "47",
            "HP": "26",
            "Atk": "-1",
            "Def": "25",
            "SpA": "20",
            "SpD": "-1",
            "Spe": "-2",
            "Gender": "M",
            "EC": "702602E6",
        },
        {
            "Advances": "4660",
            "Egg Seed": "9228D27",
            "PID": "72809680",
            "Shiny": "Yes",
            "Nature": "Bold",
            "Ability": "7",
            "HP": "-2",
            "Atk": "16",
            "Def": "15",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "6",
            "Gender": "M",
            "EC": "BAEDE6ED",
        },
        {
            "Advances": "5712",
            "Egg Seed": "E3BAFBF8",
            "PID": "147AF073",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "78",
            "HP": "25",
            "Atk": "-2",
            "Def": "-1",
            "SpA": "0",
            "SpD": "17",
            "Spe": "-2",
            "Gender": "M",
            "EC": "719C1DD",
        },
        {
            "Advances": "6091",
            "Egg Seed": "1EF52FBA",
            "PID": "5951BD50",
            "Shiny": "Yes",
            "Nature": "Lax",
            "Ability": "52",
            "HP": "21",
            "Atk": "-1",
            "Def": "16",
            "SpA": "23",
            "SpD": "-2",
            "Spe": "-2",
            "Gender": "M",
            "EC": "68922B4",
        },
        {
            "Advances": "6341",
            "Egg Seed": "19711DE9",
            "PID": "C1CE25CB",
            "Shiny": "Yes",
            "Nature": "Jolly",
            "Ability": "13",
            "HP": "-2",
            "Atk": "30",
            "Def": "-1",
            "SpA": "31",
            "SpD": "-1",
            "Spe": "2",
            "Gender": "M",
            "EC": "309D89B5",
        },
        {
            "Advances": "6394",
            "Egg Seed": "FE3B1FBD",
            "PID": "4932AD3F",
            "Shiny": "Yes",
            "Nature": "Modest",
            "Ability": "22",
            "HP": "13",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "28",
            "SpD": "13",
            "Spe": "-2",
            "Gender": "M",
            "EC": "3CDED582",
        },
        {
            "Advances": "7152",
            "Egg Seed": "142DB159",
            "PID": "8B036F05",
            "Shiny": "Yes",
            "Nature": "Relaxed",
            "Ability": "53",
            "HP": "7",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "12",
            "Spe": "2",
            "Gender": "M",
            "EC": "6298AAD3",
        },
        {
            "Advances": "9282",
            "Egg Seed": "9B6D5331",
            "PID": "FFEF1BE4",
            "Shiny": "Yes",
            "Nature": "Calm",
            "Ability": "21",
            "HP": "26",
            "Atk": "6",
            "Def": "-2",
            "SpA": "-2",
            "SpD": "-1",
            "Spe": "23",
            "Gender": "M",
            "EC": "A4BACBA5",
        },
        {
            "Advances": "9696",
            "Egg Seed": "C0485820",
            "PID": "5281B68D",
            "Shiny": "Yes",
            "Nature": "Sassy",
            "Ability": "53",
            "HP": "26",
            "Atk": "-1",
            "Def": "-1",
            "SpA": "-2",
            "SpD": "29",
            "Spe": "19",
            "Gender": "M",
            "EC": "4644661D",
        },
    ]
